export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE';

export const LOAD_SINGLE_POSTS_REQUEST = 'LOAD_SINGLE_POSTS_REQUEST';
export const LOAD_SINGLE_POSTS_SUCCESS = 'LOAD_SINGLE_POSTS_SUCCESS';
export const LOAD_SINGLE_POSTS_FAILURE = 'LOAD_SINGLE_POSTS_FAILURE';


export const POST_PAGE_ENTER = 'POST_PAGE_ENTER';
export const POST_PAGE_LEAVE = 'POST_PAGE_LEAVE';

export const RESET_HEADER = 'RESET_HEADER';
export const SHOW_POSTDATA_IN_HEADER = 'SHOW_POSTDATA_IN_HEADER';

export const SYSTEM_ERROR = 'SYSTEM_ERROR';